//
//  TagalogWords.swift
//  LanguageWordBuilder
//
//  Created by Jeremy Gurr on 11/16/20.
//

import Foundation

let tagalogWordSource = [
	"lalaki", "man",
	"babae", "woman",
	"tao", "person",
	"batang babae", "girl",
	"batang lalaki", "boy",
	"siya", "he/she",
	"sila", "they",
	"isda", "fish",
	"kabayo", "horse",
	"aso", "dog",
	"pusa", "cat",
	
	"gatas", "milk",
	"mangkok", "bowl",

	"bahay", "house",
	"restawran", "restaurant",
	"istasyon", "station",
	"paradahan", "bus stop or parking lot",

	"namin", "our",
	"kailangan", "need",
	"tuloy kayo", "stay",
	"ilan", "how many",
	"kulay", "color",
	"araw", "day",
	"pero", "but",
	"magkakapareho", "same",
	"magkakaiba", "different",
	"nasa", "at",
	"pinto", "door",
	"bisita", "guests",
	"laki", "large",
	"pila", "a line people are standing in",
	"matangkad", "tall",
	
	"buhok", "hair",
	"ulo", "head",
	"mata", "eye",
	"ilong", "nose",
	"bibig", "mouth",
	"tainga", "ear",
	"leeg", "neck",
	"bumalik", "back",
	"paa", "leg",
	"braso", "arm",
	"balikat", "shoulder",
	"siko", "elbow",
	"tuhod", "knee",
	"daliri", "finger",
	"daliri ng paa", "toe",
	
	"nauuhaw", "thirsty",
	"umiinom", "drinking",
	"uminom", "drink",
	"gutom", "hungry",
	"kumakain", "eating",
	"kumain", "eat",
	"sumasakay", "riding",
	"bumababa", "disembarking",
	"nakaupo", "sitting",
	"nakatayo", "standing",
	"pupunta", "going",
	
	"numero", "number",
	"unang", "first",
	"ikalawang", "second",
	"katlong", "third",
	"ika-apat", "fourth",

	"isa", "one",
	"dalawa", "two",
	"tatlo", "three",
	"apat", "four",
	"lima", "five",
	"anim", "six",
	"pito", "seven",
	"walo", "eight",
	"siyam", "nine",
	"sampu", "ten",
	"labing isa", "eleven",
	"labin dalawa", "twelve",
	"labin tatlo", "thirteen",
	"labing apat", "fourteen",
	"labin lima", "fifteen",
	"labing anim", "sixteen",
	"labin pito", "seventeen",
	"labin walo", "eighteen",
	"labin siyam", "nineteen",
	"dalawampu", "twenty",
]

