//
//  TagalogWords.swift
//  LanguageWordBuilder
//
//  Created by Jeremy Gurr on 11/16/20.
//

import Foundation

let tagalogWordSource = [
	["lalaki"], ["man"],
	["babae"], ["woman"],
	["tao"], ["person"],
	["batang babae"], ["girl"],
	["batang lalaki"], ["boy"],
	["siya"], ["he/she"],
	["sila"], ["they"],
	["isda"], ["fish"],
	["kabayo"], ["horse"],
	["aso"], ["dog"],
	["pusa"], ["cat"],
	
	["saan"], ["where"],
	["paano"], ["how"],
	
	["sumbrero"], ["hat"],
	["palda"], ["skirt"],
	["sapatos"], ["shoes"],
	["medyas"], ["socks"],
	["pantalon"], ["pants"],
	
	["gatas"], ["milk"],
	["mangkok"], ["bowl"],
	
	["bahay"], ["house"],
	["restawran"], ["restaurant"],
	["istasyon"], ["station"],
	["paradahan"], ["bus stop or parking lot"],
	["pos opis"], ["post office"],
	["trabajo"], ["work"],
	
	["namin"], ["our"],
	["kailangan"], ["need"],
	["tuloy kayo"], ["stay"],
	["ilan"], ["how many"],
	["kulay"], ["color"],
	["araw"], ["day"],
	["pero"], ["but"],
	["magkakapareho"], ["same"],
	["magkakaiba"], ["different"],
	["nasa"], ["at"],
	["pinto"], ["door"],
	["bisita"], ["guests"],
	["laki"], ["large"],
	["pila"], ["line", "a line people are standing in"],
	["matangkad"], ["tall"],
	["pandak"], ["short", "short (height)"],
	["lumiliko"], ["turning"],
	["dumideretso"], ["going straight"],
	["kanan"], ["right", "right (direction)"],
	["kaliwa"], ["left", "left (direction)"],
	
	["buhok"], ["hair"],
	["ulo"], ["head"],
	["mata"], ["eye"],
	["ilong"], ["nose"],
	["bibig"], ["mouth"],
	["tainga"], ["ear"],
	["leeg"], ["neck"],
	["bumalik"], ["back"],
	["paa"], ["leg"],
	["braso"], ["arm"],
	["balikat"], ["shoulder"],
	["siko"], ["elbow"],
	["tuhod"], ["knee"],
	["daliri"], ["finger"],
	["daliri ng paa"], ["toe"],
	
	["pula"], ["red"],
	["itim"], ["black"],
	["asul"], ["blue"],
	["puti"], ["white"],
	["berde"], ["green"],
	
	["nauuhaw"], ["thirsty"],
	["umiinom"], ["drinking"],
	["uminom"], ["drink"],
	["gutom"], ["hungry"],
	["kumakain"], ["eating"],
	["kumain"], ["eat"],
	["sumasakay"], ["riding"],
	["bumababa"], ["disembarking"],
	["nakaupo"], ["sitting"],
	["nakatayo"], ["standing"],
	["pupunta"], ["going"],
	["pumupunta"], ["went"],
	["pumunta"], ["will go"],
	["nakasuot"], ["wearing"],
	["naglalakad"], ["walking"],
	
	["numero"], ["number"],
	["unang"], ["first"],
	["ikalawang"], ["second"],
	["pangalawang"], ["second"],
	["katlong"], ["third"],
	["ika-apat"], ["fourth"],
	
	["isa"], ["one"],
	["dalawa"], ["two"],
	["tatlo"], ["three"],
	["apat"], ["four"],
	["lima"], ["five"],
	["anim"], ["six"],
	["pito"], ["seven"],
	["walo"], ["eight"],
	["siyam"], ["nine"],
	["sampu"], ["ten"],
	["labing isa"], ["eleven"],
	["labing dalawa"], ["twelve"],
	["labing tatlo"], ["thirteen"],
	["labing apat"], ["fourteen"],
	["labing lima"], ["fifteen"],
	["labing anim"], ["sixteen"],
	["labing pito"], ["seventeen"],
	["labing walo"], ["eighteen"],
	["labing siyam"], ["nineteen"],
	["dalawampu"], ["twenty"],
]

